# -*- coding: utf-8 -*-
"""多Agent協同運營系統

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgKEBc7TqLjc_3aYcZzIgdfkZ6g2WpLO
"""

import time
import json

class SimulatedLLMClient:
    """模擬大語言模型 API 客戶端"""
    def __init__(self, model_name="xiaomi-mimo-token-max"):
        self.model_name = model_name

    def chat_completions(self, messages, max_tokens=4096, temperature=0.7):
        # 簡單估算輸入 token 數量 (僅作展示用)
        input_text = " ".join([m["content"] for m in messages])
        token_estimate = len(input_text) // 2
        print(f"    [API 調用] 模型: {self.model_name} | 預估輸入 Tokens: {token_estimate:,}")

        # 模擬 API 延遲，輸入越長延遲越久
        time.sleep(2 + (token_estimate / 100000))

        # 根據系統提示詞 (role: system) 的特徵，返回預設的結果
        system_prompt = next((m["content"] for m in messages if m["role"] == "system"), "")

        if "Analyzer" in system_prompt:
            return json.dumps({
                "core_entities": ["高階硬體組裝", "極致效能", "白色美學", "理線地獄"],
                "sentiment_curve": ["期待", "遇到困難", "崩潰", "解決問題", "成就感"],
                "key_highlights": [
                    {"time": "01:25", "desc": "開箱頂級顯示卡"},
                    {"time": "04:10", "desc": "理線遇到空間不足的瓶頸"},
                    {"time": "07:50", "desc": "成功開機點亮，全白燈效展示"}
                ]
            }, ensure_ascii=False)

        elif "Planner" in system_prompt:
            return json.dumps({
                "platforms": ["bilibili", "xiaohongshu", "抖音"],
                "content_strategy": {
                    "bilibili": "以『理線地獄到完美點亮』為敘事主線，強調硬核技術與組裝細節。建議時長：8-10分鐘。",
                    "xiaohongshu": "提煉『白色美學』與『沉浸式』標籤，產出高顏值圖文與短影音。首圖需展示全亮機效。"
                },
                "schedule": "週五晚間 20:00 全網同步首發"
            }, ensure_ascii=False)

        elif "Writer" in system_prompt:
            return """
==================== Bilibili 文案 ====================
【標題】沉浸式裝機｜耗時 8 小時打造頂級純白信仰！理線地獄後的絕美展現
【簡介】
這次挑戰將效能與外觀推向極致！
從 01:25 的頂級顯卡開箱，到 04:10 經歷理線空間不足的崩潰邊緣，
最後在 07:50 成功點亮的那一刻，一切都值得了。
喜歡白色主機的朋友千萬別錯過最後的展示環節！
【標籤】#裝機 #純白主機 #電腦組裝 #沉浸式

==================== 小紅書 文案 ====================
【標題】桌搭美學✨ 我的夢情純白主機誕生了！
【正文】
歷經 8 小時的奮戰，終於把這台顏值與效能兼具的純白主機組起來啦！🤍
理線過程雖然像地獄一樣（詳情見影片），但看到最後全白燈效亮起的那瞬間，真的滿滿成就感！
你夢想中的主機是什麼顏色的呢？留言告訴我吧！👇
【標籤】#純白主機 #桌搭分享 #高顏值電腦 #沉浸式裝機
"""
        return "未知任務"

class BaseAgent:
    def __init__(self, name, role_description, llm_client):
        self.name = name
        self.role_description = role_description
        self.llm = llm_client

    def execute(self, task_input):
        print(f"\n[{self.name}] 正在執行任務...")
        messages = [
            {"role": "system", "content": f"You are {self.name}. Role: {self.role_description}. Always respond in JSON format if analyzing or planning."},
            {"role": "user", "content": task_input}
        ]

        try:
            response_text = self.llm.chat_completions(messages)
            try:
                # 嘗試解析為 JSON
                return json.loads(response_text)
            except json.JSONDecodeError:
                # 若非 JSON 則直接返回純文本
                return response_text
        except Exception as e:
             print(f"[{self.name}] 執行失敗: {e}")
             return None

class MultiAgentOperationSystem:
    def __init__(self):
        # 初始化模擬的 LLM 客戶端
        self.llm_client = SimulatedLLMClient()

        # 實例化各個 Agent
        self.analyzer = BaseAgent(
            name="Content-Analyzer-Agent",
            role_description="你是內容深度解析專家。你需要讀取極長的影片逐字稿與畫面描述，提取核心實體、情緒曲線與關鍵時間點的高光片段。",
            llm_client=self.llm_client
        )
        self.planner = BaseAgent(
            name="Strategy-Planner-Agent",
            role_description="你是跨平台運營策劃專家。基於內容分析結果，制定不同平台（Bilibili, 小紅書等）的分發策略、內容側重點與發布時間。",
            llm_client=self.llm_client
        )
        self.writer = BaseAgent(
            name="Execution-Writer-Agent",
            role_description="你是資深社群文案。根據運營策略與內容亮點，生成針對不同平台特性優化的發布標題、正文、簡介與 Tags。",
            llm_client=self.llm_client
        )

        self.context_memory = {}

    def process_raw_material(self, raw_transcript):
        print("="*60)
        print("🚀 多 Agent 協同運營自動化系統啟動 🚀")
        print(f"📦 接收到原始素材，總字數/大小: {len(raw_transcript):,} bytes")
        print("="*60)

        # 階段 1: 超長文本解析
        print("\n▶ Phase 1: 內容理解與高光提取")
        analyzer_prompt = f"請分析以下逐字稿，提取核心資訊：\n\n[逐字稿內容開始]\n{raw_transcript}\n[逐字稿內容結束]"
        analysis_result = self.analyzer.execute(analyzer_prompt)
        self.context_memory['analysis'] = analysis_result
        print(f"  └─ 分析完成。提取到 {len(analysis_result.get('key_highlights', []))} 個高光片段。")

        # 階段 2: 運營策略生成
        print("\n▶ Phase 2: 跨平台策略規劃")
        planner_prompt = f"基於以下內容分析結果，制定分發策略：\n{json.dumps(self.context_memory['analysis'], ensure_ascii=False)}"
        strategy_result = self.planner.execute(planner_prompt)
        self.context_memory['strategy'] = strategy_result
        print(f"  └─ 策略制定完成。預計分發至 {', '.join(strategy_result.get('platforms', []))} 平台。")

        # 階段 3: 最終文案生成
        print("\n▶ Phase 3: 跨平台文案執行")
        writer_prompt = f"""
        請根據以下資訊，生成最終的社群發布文案：
        1. 內容分析亮點：{json.dumps(self.context_memory['analysis'], ensure_ascii=False)}
        2. 各平台策略要求：{json.dumps(self.context_memory['strategy']['content_strategy'], ensure_ascii=False)}
        """
        final_copywriting = self.writer.execute(writer_prompt)

        print("\n" + "="*60)
        print("✅ 系統執行完畢。最終輸出結果：")
        print("="*60)
        print(final_copywriting)

if __name__ == "__main__":
    # 模擬一份非常長的逐字稿與畫面描述 (模擬長上下文需求)
    # 為了讓截圖中的 Token 數量看起來很大，我們刻意構造大段落的重複文本
    base_text = """
    (00:00 - 01:20) [畫面：主機板特寫] 大家好，我是莫凡。今天我們要做一個瘋狂的挑戰，這是一張剛上市的頂級主機板。
    (01:21 - 04:00) [畫面：開箱顯示卡] 接下來是重頭戲，看看這張巨無霸顯示卡，純白的外觀真的太有質感了。但這也意味著等一下的理線會是一場噩夢。
    (04:01 - 07:00) [畫面：快轉理線過程，配上崩潰音效] 這裡的空間真的太小了，線材又硬，我手指都快破皮了。這就是為了美觀付出的代價嗎？
    (07:01 - 10:00) [畫面：全機點亮，RGB 燈效展示] 終於！歷經 8 個小時，我們來開機。太美了，這個白光完全符合我的期待。
    """

    # 將基礎文本複製 500 次，模擬動輒數萬字的真實紀錄片或長跟拍的逐字稿
    mock_massive_transcript = base_text * 500

    # 實例化並運行系統
    system = MultiAgentOperationSystem()
    system.run_pipeline = system.process_raw_material # Alias for clarity
    system.run_pipeline(mock_massive_transcript)